# This action controls the deployment to prod branch. 
# It triggers whenever something is pushed to prod branch (either it is a new commit or it is a merge request from lower branches (dev))
# It only passes the merge requests. No direct pushes to prod are allowed and will be stoped!

name: dev_to_prod

on:
    push:
        branches:
            - "main" # Specific branch and operation. IN this case, push to prod branch.
    
    workflow_dispatch: # Allow manual triggering from the Actions tab if needed. By default, this action runs automatically whenever something is pushed to prod branch.

jobs:
    build:
        runs-on: ubuntu_latest

        # Define variables here
        env:
            push_to_prod: "false" # If push_to_prod = false, all direct pushes to prod branch will be stopped.

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check if this is a direct push to prod branch or merge request
              run: |
                echo "Checking if this is a merge request or direct push..."
                # Get the commit message to check if it contains a merge message
                COMMIT_MSG=$(git log -1 --pretty=%B)
                echo "Last commit message: $COMMIT_MSG"

                if [[ "$COMMIT_MSG" != "Merge branch"*]]; then
                    if [[ "$push_to_prod" == "false" ]]; then
                        echo "Direct push to prod branch is disabled. Please use a merge from lower lever branch (dev)."
                        exit 1
                    fi
                else
                    echo "This is a merge commit, continuing the workflow..."
                fi
            
            - name: Run the build process
              run: |
                echo "Running the deploy to prod process..."