# This action controls the deployment to prod branch.
# It triggers whenever something is pushed to the prod branch (either it is a new commit or it is a merge request from lower branches (dev))
# It only passes the merge requests. No direct pushes to prod are allowed and will be stopped!

name: dev_to_prod

on:
    push:
        branches:
            - "main" # Trigger this on push to the prod branch (main).
    
    workflow_dispatch: # Allow manual triggering from the Actions tab if needed. By default, this action runs automatically whenever something is pushed to prod branch.

jobs:
    build:
        runs-on: ubuntu-latest

        # Define environment variables here
        env:
            push_to_prod: "false" # If push_to_prod = false, all direct pushes to prod branch will be stopped.

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check if this is a direct push to prod branch or merge request
              run: |
                echo "Checking if this is a merge request or direct push..."
                
                # Check the context of the push event
                if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
                    # If the event is a push to main, it's a direct push
                    if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
                        # This is a direct push to `main`, and we're blocking it.
                        echo "Direct push to prod branch is disabled. Please use a merge from a lower-level branch (dev)."
                        exit 1
                    fi
                fi

                # If the event is a pull request (merge), proceed
                if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
                    echo "This is a merge commit from a PR, continuing the workflow..."
                else
                    # This is an invalid push, exit
                    echo "This is a direct push, which is blocked."
                    exit 1
                fi

            - name: Run the build process
              run: |
                echo "Running the deploy to prod process..."
